Add initial documentation

diff --git a/.github/workflows/pr_code_changes.yaml b/.github/workflows/pr_code_changes.yaml
--- a/.github/workflows/pr_code_changes.yaml
+++ b/.github/workflows/pr_code_changes.yaml
@@ -20,3 +20,29 @@ jobs:
           run: |
             pip install ruff
             ruff check --fix --exit-zero
+  Test:
+    runs-on: ubuntu-latest
+    steps:
+        - uses: actions/checkout@v4
+        - name: Install uv
+          uses: astral-sh/setup-uv@v5
+
+        - name: Set up Python
+          uses: actions/setup-python@v2
+          with:
+              python-version: '3.11'
+        - name: Install dependencies
+          run: make install
+        - name: Run tests
+          run: make test
+        - name: Build documentation
+          run: make documentation
+        - name: Check documentation build
+          run: |
+            for notebook in $(find docs/_build/jupyter_execute -name "*.ipynb"); do
+              if grep -q '"output_type": "error"' "$notebook"; then
+                echo "Error found in $notebook"
+                cat "$notebook"
+                exit 1
+              fi
+            done
